trigger:
  paths:
    include:
      - '*'

jobs:
- job: linux
  pool: {vmImage: 'ubuntu-20.04'}
  steps:
    - task: UsePythonVersion@0
      displayName: Set Python version (3.X)
      inputs:
        versionSpec: '3.x'
        addToPath: true
        architecture: 'x64'
    - task: CmdLine@2
      displayName: Install dependencies
      inputs:
        script: |
          set -o errexit
          pip install --upgrade pip
          pipx install cibuildwheel==2.1.1
          pipx install conan
          source ~/.profile
          echo $(conan --version)
    # - task: CmdLine@2
    #   displayName: Install dependencies
    #   inputs:
    #     script: |
    #       set -o errexit
    #       python3 -m pip install --upgrade pip
    #       pip3 install cibuildwheel==2.1.1
    - task: CmdLine@2
      displayName: Build wheels
      inputs:
        script: cibuildwheel --output-dir wheelhouse .
      env:
        CIBW_BEFORE_ALL: '>
          pipx install conan && 
          conan profile update settings.compiler.libcxx=libstdc++11 default && 
          conan install pybind11/2.7.1@
          find . -name "libpython3.8.so"'
        CIBW_BUILD: cp38-*
        CIBW_SKIP: pp*
    - task: PublishBuildArtifacts@1
      displayName: Publish Wheels
      inputs:
        PathtoPublish: 'wheelhouse'
        ArtifactName: 'linux'
        publishLocation: 'Container'

- job: windows
  condition: False
  pool: {vmImage: 'windows-2019'}
  steps:
    - task: UsePythonVersion@0
      displayName: Set Python version (3.X)
      inputs:
        versionSpec: '3.x'
        addToPath: true
        architecture: 'x64'
    - task: CmdLine@2
      displayName: Install dependencies
      inputs:
        script: |
          set -o errexit
          python -m pip install --upgrade pip
          pip install cibuildwheel==2.1.1
    - task: CmdLine@2
      displayName: Build wheels
      inputs:
        script: cibuildwheel --output-dir wheelhouse .
    - task: PublishBuildArtifacts@1
      displayName: Publish Wheels
      inputs:
        PathtoPublish: 'wheelhouse'
        ArtifactName: 'windows'
        publishLocation: 'Container'

- job: macos
  condition: False
  pool: {vmImage: 'macOS-10.15'}
  steps:
    - task: UsePythonVersion@0
      displayName: Set Python version (3.X)
      inputs:
        versionSpec: '3.x'
        addToPath: true
        architecture: 'x64'
    - task: CmdLine@2
      displayName: Install dependencies
      inputs:
        script: |
          set -o errexit
          python3 -m pip install --upgrade pip
          python3 -m pip install cibuildwheel==2.1.1
    - task: CmdLine@2
      displayName: Build wheels
      inputs:
        script: cibuildwheel --output-dir wheelhouse .
    - task: PublishBuildArtifacts@1
      displayName: Publish Wheels
      inputs:
        PathtoPublish: 'wheelhouse'
        ArtifactName: 'mac'
        publishLocation: 'Container'
    

